apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-demo-application
  namespace: argocd
spec:
  destination:
    namespace: argo-demo
    server: https://kubernetes.default.svc
  project: project-role  
  source:
    path: kubernetes-manifest
    repoURL: https://github.com/samfolbs/ArgoCD_WebApp_Deployment.git  
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
